@extends('Templates/WiTemplate')
<?php
if (session_id() == '') {
    session_start();
}
?>
@section('title')
Testing Manage
@stop

@section('head')
<script type="text/javascript">
    var del = false;
    function gettgID(id) {
        document.getElementById('tgid').value = id;
        del = true;
    }

    function getAnID(id) {
        document.getElementById('anid').value = id;
        del = true;
    }



    function viewTests(id) {
        tgid = id; 
        
        document.getElementById('tgname').value = document.getElementById('name+'+id).value;
        document.getElementById('tgprice').value = document.getElementById('price+'+id).value;
        document.getElementById('time').value = document.getElementById('time+'+id).value;
        document.getElementById('tgcost').value = document.getElementById('cost+'+id).value;
    
    //get comment  
    $.ajax({
    url: "gettgcomment",
            type: 'POST',
            data: {'tgid': id, '_token': $('input[name=_token]').val()},
            success: function(result) {
            document.getElementById('commentx').innerHTML = result;
            }
    });
    //
        
        
    $.ajax({
    url: "testGroupsubmit",
            type: 'POST',
            data: {'submit': 'getTests', 'tgid': id, '_token': $('input[name=_token]').val()},
            success: function(result) {
            if (result !== "") {
            var div = document.getElementById('TestList');
            div.innerHTML = result;
            } else {
            var div = document.getElementById('TestList');
            div.innerHTML = "<p>Testings not found!</p>";
            }
            }
    });
    }

    function validate(){
        if (del){
            var x = confirm("Dou you want to delete this record?");
            if (x){
                return true;
            } else{
                del = false;
                return false;                
            }
        }
    }
    
    function printGroupTable() { 
                var body = $("#tg_table").html();
                var newWin = window.open('', 'Print-Window');
                newWin.document.open();
                newWin.document.write("<html><head><title>MLWS - Print</title><head><body onload='window.print()'><center><h2>MLWS Testing Details</h2><div style='width:800px'><hr/><br/>" + body + "</div><br/><hr/><p style='font-size:12px' align='right'>Generated By MLWS. Powered by Appex Solutions. www.appexsl.com</p></center></body></html>");
                newWin.document.close();
                setTimeout(function () {
                    newWin.close();
                }, 2000);

            }
    var tgid;       
    function updateComment(){
        
                var cmt = $('#commentx').val();
//                alert(cmt);
//                alert($('#comment').html().replace("&lt;","<").replace("&gt;",">")); 
                $.ajax({
                    url: "updatetgcomment",
                    type: 'POST',
                    data: {'tgid': tgid,'comment': cmt, '_token': $('input[name=_token]').val()},
                    success: function(result) {
                        alert(result);
                    }
                });
            }
    

</script>
@stop

@section('body')
<?php
    if (isset($_SESSION['lid']) & isset($_SESSION['luid'])) {
?>
<blockquote>
    <?php
    $cuSymble = $_SESSION['cuSymble'];
    ?>

    <h2 class="pageheading">Manage Testing Groups</h2>
    <p>&nbsp;</p>


    <table width="100%">
        <tr valign="top">
        <form action="testGroupsubmit" method="post" onsubmit="return validate()">
            <td width="25%">
                <p class="tableHead">Add new Testing Group</p>

                <table width="100%">
                    <tr>
                        <td>                                
                            Name
                        </td>
                        <td>
                            <input type="text" name="tgname" id="tgname" class="input-text" style="width: 150px;">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Price {{ $cuSymble }}
                        </td>
                        <td>
                            <input type="text" name="tgprice" id="tgprice" class="input-text" pattern="[0-9]{1,10}" title="Enter valid price for new test group!" style="width: 150px;" >
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Cost {{ $cuSymble }}
                        </td>
                        <td>
                            <input type="text" name="tgcost" id="tgcost" class="input-text" pattern="[0-9]{1,10}" title="Enter valid price for new test group!" style="width: 150px;" value="0" >
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            Time(Hrs)
                        </td>
                        <td>
                            <input type="text" name="time" id="time" class="input-text" style="width: 150px;">
                        </td>
                    </tr>
                    <tr valign="top">
                        <td>
                            Comment Section HTML
                        </td>
                        <td>
                            <textarea id="commentx" name="comment" rows="10" class="text-area" style="width: 150px;"></textarea>
                            <a href="https://html-online.com/editor" target="_blank" style="float: left;">HTML Editor</a> <input type="button" class="btn" style="margin:0px; float: right;" value="Update" onclick="updateComment()">
                        </td>
                    </tr> 
                    <tr>
                        <td>

                        </td>
                        <td>
                            <input type="submit" class="btn" style="margin-left: 0px; width: 170px;" name="submit" value="Add Group">
                            {{ $msg or '' }}
                        </td>
                    </tr>

                </table>
            </td>
        </form>
        <td>
            <form action="testGroupsubmit" method="POST" onsubmit="return validate()">
                <div class="pageTableScope2" style="margin-left: 30px; border-left-color: #001092; border-left-style: solid; border-left-width: 1px; padding-left: 20px">
                    <p style="float: left" class="tableHead">View Testing Groups</p>
                    <p style="float: right;">
                        <input type="button" value="Print Table" class="btn" style="margin: 0px; width: 120px;" onclick="printGroupTable()">
                        <input type="submit" name="submit" value="Update Table" class="btn" style="margin: 0px;"></p>
                    <table id="tg_table" border="0" cellpadding="0" cellspacing="0">
                        <tr>
                            <td width="482" height="70" valign="top">
                                <table width="414" border="1" cellpadding="0" cellspacing="0" class="TableWithBorder">
                                    <tr>
                                        <th width="37%" class="viewTHead" scope="col">Group Name</th>
                                        <th width="11%" class="viewTHead" scope="col">Price {{ $cuSymble }}</th>
                                        <th width="10%" class="viewTHead" scope="col">Cost {{ $cuSymble }}</th>
                                        <th width="21%" class="viewTHead" scope="col">Time Duration (Hours)</th>
                                    </tr>

                                    <?php
                                    $Result = DB::select("select * from Testgroup where Lab_lid = '" . $_SESSION['lid'] . "' order by name ASC");
                                    foreach ($Result as $res) {
                                        ?>
                                        <tr>
                                            <td height="26"><input type="text" name="name+{{ $res->tgid }}" id="name+{{ $res->tgid }}" value="{{ $res->name }}" size="15"></td>
                                            <td><input type="text" name="price+{{ $res->tgid }}" id="price+{{ $res->tgid }}" value="{{ $res->price }}" size="5"></td>
                                            <td><input type="text" name="cost+{{ $res->tgid }}" id="cost+{{ $res->tgid }}" value="{{ $res->cost }}" size="5"></td>
                                            <td><input type="text" name="time+{{ $res->tgid }}" id="time+{{ $res->tgid }}" value="{{ $res->testingtime }}" size="10">
                                            </td>
                                            <td width="19%"><input type="button" name="{{ $res->tgid }}" class="btn" style="margin:0px;" value="View Testings" onClick="viewTests(name)"></td>

                                            <td width="23%"><input id="{{ $res->tgid }}" type="submit" class="btn" style="margin:0px;" name="submit" value="Delete" onClick="gettgID(id)">

                                            </td>
                                        </tr>
                                    <?php } ?>
                                </table>
                                <input type="hidden" id="tgid" name="tgid" value="">
                            </td>
                            <td width="400" valign="top">
                                <div id="TestList">
                                </div>
                            </td>
                        </tr>
                    </table>
                </div>
            </form>
        </td>
        </tr>            
    </table> 
    <hr/>
    <h2 class="pageheading">Manage Analyzers</h2>
    <p>&nbsp;</p>

    <form action="analyzermanagesubmit" method="post" onsubmit="return validate()">
        <table width="100%">
            <tr valign="top">
                <td width="25%">
                    <p class="tableHead">Add new Analyzer</p>

                    <table width="100%">
                        <tr>
                            <td width="150px">                                
                                Name
                            </td>
                            <td>
                                <input type="text" name="anname" class="input-text" />
                            </td>
                        </tr>                        
                        <tr>
                            <td>

                            </td>
                            <td>
                                <input type="submit" class="btn" style="margin-left: 0px; width: 190px;" name="submit" value="Add Analyzer">
                                {{ $msg or '' }}
                            </td>
                        </tr>

                    </table>
                </td>

                <td>
                    <div class="pageTableScope2" style="margin-left: 30px; border-left-color: #001092; border-left-style: solid; border-left-width: 1px; padding-left: 20px">
                        <p class="tableHead">View Analyzers</p>
                        <table border="0" cellpadding="0" cellspacing="0">
                            <tr>
                                <td width="482" height="70" valign="top">
                                    <table width="414" border="1" cellpadding="0" cellspacing="0" class="TableWithBorder">
                                        <tr>
                                            <th width="37%" class="viewTHead" scope="col">Analyzer Name</th>
                                        </tr>

                                        <?php
                                        $Result = DB::select("select * from analyzers where Lab_lid = '" . $_SESSION['lid'] . "' and status = '1'");
                                        foreach ($Result as $res) {
                                            ?>
                                            <tr>
                                                <td height="26"><input type="text" name="name+{{ $res->anid }}" value="{{ $res->name }}" style="width: 95%"></td>
                                                <td width="23%"><input type="submit" class="btn" style="margin:0px;" name="submit" value="Delete" onClick="getAnID('{{ $res->anid }}')">

                                                </td>
                                            </tr>
                                        <?php } ?>
                                    </table>
                                    <input type="hidden" id="anid" name="anid" value="">
                                </td>
                                <td width="400" valign="top">
                                    <div id="TestList">
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </td>
            </tr>            
        </table>
    </form>




</blockquote>
<?php
    }
?>
@stop