@extends('Templates/WiTemplate')
<?php
if (session_id() == '') {
    session_start();
}
?>
@section('title')
Manage Expenses
@stop

@section('head')
<script type="text/javascript">
    window.onload = loadDate;
    function loadDate() {

        $("#sc01").hide();
        $("#sc02").hide();

        document.getElementById('date').valueAsDate = new Date();
        document.getElementById('date1').valueAsDate = new Date();
        document.getElementById('date2').valueAsDate = new Date();
        document.getElementById('scdate').valueAsDate = new Date();


        searchExpenses();

//        search();
    }

    var del = false;
    function gettgID(id) {
//        alert(id)
        document.getElementById('tgid').value = id;
        del = true;
    }

    function getAnID(id) {
        document.getElementById('anid').value = id;
        del = true;
    }

    function viewTests(id) {
        tgid = id;

        document.getElementById('tgname').value = document.getElementById('name+' + id).value;
        document.getElementById('tgprice').value = document.getElementById('price+' + id).value;
        document.getElementById('time').value = document.getElementById('time+' + id).value;

        //get comment  
        $.ajax({
            url: "gettgcomment",
            type: 'POST',
            data: {'tgid': id, '_token': $('input[name=_token]').val()},
            success: function (result) {
                document.getElementById('commentx').innerHTML = result;
            }
        });
        //


        $.ajax({
            url: "expensessubmit",
            type: 'POST',
            data: {'submit': 'getTests', 'tgid': id, '_token': $('input[name=_token]').val()},
            success: function (result) {
                if (result !== "") {
                    var div = document.getElementById('TestList');
                    div.innerHTML = result;
                } else {
                    var div = document.getElementById('TestList');
                    div.innerHTML = "<p>Testings not found!</p>";
                }
            }
        });
    }

    function validate() {
        if (del) {
            var x = confirm("Dou you want to delete this record?");
            if (x) {
                return true;
            } else {
                del = false;
                return false;
            }
        }
    }

    function printGroupTable() {

        //hide buttons
        $('.btn').hide();

        var body = $("#tg_table").html();
        var date = $("#date1").val() + " TO " + $("#date2").val();
        var branch = $("#sbranch").val();

        var total = $("#totexp").html();

        var newWin = window.open('', 'Print-Window');
        newWin.document.open();
        newWin.document.write("<html><head><title>MLWS - Print</title><head><body onload='window.print()'><center><h2>Day Expenses Report</h2><p>Date : " + date + "</p><p>Branch : " + branch + "</p><div style='width:800px'><hr/><br/>" + body + "</div> <h3>" + total + "</h3> <br/><hr/><p style='font-size:12px' align='center'>Generated By MLWS. Powered by Appex Solutions. www.appexsl.com</p></center></body></html>");
        newWin.document.close();
        setTimeout(function () {
            newWin.close();
        }, 2000);

        //hide buttons
        $('.btn').show();
    }
    var tgid;
    function updateComment() {

        var cmt = $('#commentx').val();
        $.ajax({
            url: "updatetgcomment",
            type: 'POST',
            data: {'tgid': tgid, 'comment': cmt, '_token': $('input[name=_token]').val()},
            success: function (result) {
                alert(result);
            }
        });
    }

    function setBranchCode() {
        $("#brcode").val($("#brcodex").val());
    }

    function searchExpenses() {

        var date1 = $("#date1").val();
        var date2 = $("#date2").val();
        var branch = $("#sbranch").val();
        var desc = $("#description").val();
        
        var ssup = $("#ssup").val();
        var cdate = $("#cdate").val();
        
//        alert(cdate);

        $.ajax({
            url: "searchexpenses",
            type: 'POST',
            data: {'do': date1, 'dt': date2, 'br': branch, 'dec': desc, 'sup': ssup, 'cdate': cdate, '_token': $('input[name=_token]').val()},
            success: function (result) {
                var arr = result.split("/#/#/#");
                $("#exptable").html(arr[0]);
                $("#totexpamount").html(arr[1]);
            }
        });
    }

    function clickBCCheckBox() {


        if ($("#sc01").is(":visible")) {
            $("#sc01").hide();
            $("#sc02").hide();
        } else {
            $("#sc01").show();
            $("#sc02").show();
        }
    }

    function clickondcno() {

        var sdate = $("#scdate").val();
        var sno = $("#scno").val();


        $.ajax({
            url: "searchexpensesbillc",
            type: 'POST',
            data: {'sdate': sdate, 'sno': sno, '_token': $('input[name=_token]').val()},
            success: function (result) {
//                alert(result);

                $("#tgprice").val(result);
            }
        });
    }


</script>
@stop

@section('body')
<?php
if (isset($_SESSION['lid']) & isset($_SESSION['luid'])) {
    ?>
    <blockquote>
        <?php
        $cuSymble = $_SESSION['cuSymble'];
        ?>

        <h2 class="pageheading">Manage Day to Day Expenses</h2>
        <p>&nbsp;</p>


        <table width="100%">
            <tr valign="top">
            <form action="expensessubmit" method="post" onsubmit="return validate()">
                <td width="25%">
                    <p class="tableHead">Add new Expense</p>

                    <table width="100%" cellspacing="5">
                        <tr>
                            <td>                                
                                Date
                            </td>
                            <td>
                                <input type="date" name="date" id="date" class="input-text" style="width: 150px;">
                            </td>
                        </tr>

                        <tr>
                            <td>                                
                                Vendor
                            </td>
                            <td>
                                <input type="text" name="sup" id="sup" class="input-text" style="width: 150px;" list="suplist">
                                <datalist id="suplist">
                                    <?php
                                    $Resultdl = DB::select("select vendor from payments where Lab_lid = '" . $_SESSION['lid'] . "' group by vendor");
                                    foreach ($Resultdl as $resdl) {
                                        ?>
                                        <option> <?php echo $resdl->vendor; ?> </option> 
                                    <?php } ?>
                                </datalist>
                            </td>
                        </tr>

                        <tr valign="top">
                            <td>
                                Description
                            </td>
                            <td>
                                <input type="text" name="desc" id="desc" list="desclist" class="input-text" style="width: 150px;">
                                <datalist id="desclist">
                                    <?php
                                    $Resultdl = DB::select("select reason from payments where Lab_lid = '" . $_SESSION['lid'] . "' group by reason");
                                    foreach ($Resultdl as $resdl) {
                                        ?>
                                        <option> <?php echo $resdl->reason; ?> </option> 
                                    <?php } ?>
                                </datalist>
                            </td>
                        </tr>

                        <tr>
                            <td>                                
                                Cheque NO
                            </td>
                            <td>
                                <input type="text" name="cno" id="cno" class="input-text" style="width: 150px;">
                            </td>
                        </tr>
                        
                        <tr>
                            <td>                                
                                Cheque Date
                            </td>
                            <td>
                                <input type="date" name="cdt" id="cdt" class="input-text" style="width: 150px;">
                            </td>
                        </tr>

                        <tr>
                            <td>
                                Price {{ $cuSymble }}
                            </td>
                            <td>
                                <input type="text" name="tgprice" id="tgprice" class="input-text" pattern="[0-9]{1,10}" title="Enter valid price for new test group!" style="width: 150px;" >
                            </td>
                        </tr>

                        <tr>
                            <td>
                                Branch
                            </td>
                            <td>
                                <select class="select-basic" id="brcodex" style="width: 173px;" onchange="setBranchCode()">
                                    <option value="ALL"></option> 

                                    <?php
                                    $rs = DB::select("select name, code from labbranches where lab_lid = '" . $_SESSION['lid'] . "'");
                                    foreach ($rs as $rsb) {
                                        ?>
                                        <option value="{{ $rsb->code }}">{{ $rsb->name }}</option>
                                        <?php
                                    }
                                    ?> 

                                </select>
                                <input type="hidden" name="brcode" id="brcode" class="input-text" style="width: 150px;" >
                            </td>
                        </tr>

                        <tr id="billcanceldiv">
                            <td>
                                <br/>
                                <input type="checkbox" id="bccheck" onchange="clickBCCheckBox()"/> Bill Cancellation 
                            </td>
                        </tr>

                        <tr id="sc01">
                            <td>
                                Sample Date
                            </td>
                            <td>
                                <input type="date" id="scdate" name="scdate" class="input-text" style="width: 150px;">
                            </td>
                        </tr>

                        <tr id="sc02">
                            <td>
                                Sample NO
                            </td>
                            <td>
                                <input type="text" id="scno" name="scno" onkeyup="clickondcno()" class="input-text" style="width: 150px;">
                            </td>
                        </tr>

                        <tr>
                            <td>

                            </td>
                            <td>
                                <input type="submit" class="btn" style="margin-left: 0px; width: 170px;" name="submit" value="Add Expense">
                                <span style="color: Blue;">{{ $msg or '' }}</span>
                            </td>
                        </tr>

                    </table>
                </td>
            </form>
            <td> 
                <form action="expensessubmit" method="POST"> 
                    <div class="pageTableScope2" style="margin-left: 30px; border-left-color: #001092; border-left-style: solid; border-left-width: 1px; padding-left: 20px; height: 500px;">
                        <p style="float: left" class="tableHead">View Day Expenses</p>
                        <br/>

                        <table>
                            <tr>
                                <td>Date From <br/> <input type="date" class="input-text" id="date1"/></td>
                                <td>TO <br/> <input type="date" class="input-text" id="date2"/></td>
                                <td>Branch : <br/> 
                                    <select id="sbranch" class="select-basic">
                                        <option value="ALL">ALL</option> 

                                        <?php
                                        $rs = DB::select("select name, code from labbranches where lab_lid = '" . $_SESSION['lid'] . "'");
                                        foreach ($rs as $rsb) {
                                            ?>
                                            <option value="{{ $rsb->code }}">{{ $rsb->name }}</option>
                                            <?php
                                        }
                                        ?> 
                                    </select>
                                </td>
                                <td>
                                    Description : <br/> <input type="text" class="input-text" id="description" list="desclistx" /> 
                                    <datalist id="desclistx">
                                        <?php
                                        $Resultdl = DB::select("select reason from payments where Lab_lid = '" . $_SESSION['lid'] . "' group by reason");
                                        foreach ($Resultdl as $resdl) {
                                            ?>
                                            <option> <?php echo $resdl->reason; ?> </option>  
                                        <?php } ?>
                                    </datalist>

                                </td>
                                <td>
                                    <input type="button" value="Search" onclick="searchExpenses()" class="btn"/>
                                </td>
                            </tr>
                            <tr>
                                <td>Vendor : <br/> 
                                    <select id="ssup" class="select-basic">
                                        <option></option> 

                                        <?php
                                        $Resultdl = DB::select("select vendor from payments where Lab_lid = '" . $_SESSION['lid'] . "' group by vendor");
                                        foreach ($Resultdl as $resdl) {
                                            ?>
                                            <option> <?php echo $resdl->vendor; ?> </option> 
                                        <?php } ?>
                                    </select>
                                </td>
                                <td>
                                    Cheque Date : <input type="date" class="input-text" id="cdate"/>

                                </td>

                            </tr>

                        </table>


                        <hr/>
                        <p style="float: right;">
                            <input type="button" value="Print Table" class="btn" style="margin: 0px; width: 120px;" onclick="printGroupTable()">
                            <!--<input type="submit" name="submit" value="Update Table" class="btn" style="margin: 0px;"></p>-->

                        <table id="tg_table" border="0" cellpadding="0" cellspacing="0" >
                            <tr>
                                <td valign="top">
                                    <table id="exptable" width="900" border="1" cellpadding="0" cellspacing="0" class="TableWithBorder" style="font-family: serif;">

                                    </table> 

                                    <input type="hidden" id="tgid" name="tgid" value="">
                                </td>
                                <td width="400" valign="top">
                                    <div id="TestList">
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </form>
            </td>
            </tr>            
        </table> 
        <hr/>

        <h2 id="totexp" style="font-family: serif; color: #001092;">Total Expenses Amount Rs. <span id="totexpamount" style="font-weight: bold;">  </span> </h2> 
        <hr/> 
    </blockquote>
    <?php
}
?>
@stop