@extends('Templates/WiTemplate')
<?php
if (session_id() == '') {
    session_start();
}
?>
@section('title')
Manage Wastage
@stop

@section('head')
<script type="text/javascript">
    window.onload = loadDate;
    function loadDate() {

        document.getElementById('date1').valueAsDate = new Date();
        document.getElementById('date2').valueAsDate = new Date();
        document.getElementById('date').valueAsDate = new Date();

        searchExpenses();

    }


    function gettgID(id) {
     var x = confirm("Are you sure you want to delete this record?");

     if(x == 1){
        $.ajax({
            url: "Wastagessubmit",
            type: 'POST',
            data: {'submit': 'DeteleItem','id': id, '_token': $('input[name=_token]').val()},
            success: function (result) {
                alert("Record Deleted!");
                searchExpenses();
            }
        });
     }
    }
    
    function printGroupTable() {

        //hide buttons
        $('.btn').hide();

        var body = $("#tg_table").html();
        var date = $("#date1").val() + " TO " + $("#date2").val();
        var branch = $("#sbranch").val();

        var total = $("#totexp").html();

        var newWin = window.open('', 'Print-Window');
        newWin.document.open();
        newWin.document.write("<html><head><title>MLWS - Print</title><head><body onload='window.print()'><center><h2>Day Wastages Report</h2><p>Date : " + date + "</p><p>Branch : " + branch + "</p><div style='width:800px'><hr/><br/>" + body + "</div> <h3>" + total + "</h3> <br/><hr/><p style='font-size:12px' align='center'>Generated By MLWS. Powered by Appex Solutions. www.appexsl.com</p></center></body></html>");
        newWin.document.close();
        setTimeout(function () {
            newWin.close();
        }, 2000);

        //hide buttons
        $('.btn').show();
    }
    var tgid;


    function searchExpenses() {

        var date1 = $("#date1").val();
        var date2 = $("#date2").val();
        var desc = $("#description").val();
        
        var ssup = $("#ssup").val();
        var cdate = $("#cdate").val();
        
//        alert(cdate);

        $.ajax({
            url: "searchWastages",
            type: 'POST',
            data: {'do': date1, 'dt': date2,'dec': desc, 'sup': ssup, 'cdate': cdate, '_token': $('input[name=_token]').val()},
            success: function (result) {
                var arr = result.split("/#/#/#");
                $("#exptable").html(arr[0]);
                $("#totexpamount").html(arr[1]);
            }
        });
    }




</script>
@stop

@section('body')
<?php 
if (isset($_SESSION['lid']) & isset($_SESSION['luid'])) {
    ?>
    <blockquote>
        <?php
        $cuSymble = $_SESSION['cuSymble'];
        ?>

        <h2 class="pageheading">Manage Material Wastag</h2>
        <p>&nbsp;</p>


        <table width="100%">
            <tr valign="top">
            <form action="Wastagessubmit" method="post" onsubmit="return validate()">
                <td width="25%">
                    <p class="tableHead">Add new wastage</p>

                    <table width="100%" cellspacing="5">
                        <tr>
                            <td>                                
                                Wastage Date
                            </td>
                            <td>
                                <input type="date" name="date" id="date" class="input-text" style="width: 150px;">
                            </td>
                        </tr>

                        <tr>
                            <td>                                
                                Wastage Type
                            </td>
                            <td>
                                <select name="wtype" id="wtype" class="select-basic" onchange="getDesc()" style="width: 175px;">
                                    <option></option>
                                    <?php
                                    $Resultdl = DB::select("select * from waste_category");
                                    foreach ($Resultdl as $resdl) {
                                        ?>
                                        <option value="<?php echo $resdl->id; ?>"> <?php echo $resdl->name; ?> </option> 
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>

                        

                        <tr valign="top">
                            <td>
                                Reason / Descreption
                            </td>
                            <td>
                                <input type="text" name="desc" id="desc" list="desclist" class="input-text" style="width: 150px;">
                                <datalist id="desclist">
                                    <?php
                                    $Resultdl = DB::select("select reason from wastage group by reason");
                                    foreach ($Resultdl as $resdl) {
                                        ?>
                                        <option> <?php echo $resdl->reason; ?> </option> 
                                    <?php } ?>
                                </datalist>
                            </td>
                        </tr>

                        <tr valign="top">
                            <td>
                                Material
                            </td>
                            <td>
                                <select id="matlist" name="mat" class="input-text" style="width: 175px;">
                                    <?php
                                    $Resultdl = DB::select("SELECT a.name,b.lmid FROM materials a,Lab_has_materials b where b.materials_mid = a.mid and b.lab_lid = '" . $_SESSION['lid'] . "' order by a.name ASC");
                                    foreach ($Resultdl as $resdl) {
                                        ?>
                                        <option value="<?php echo $resdl->lmid; ?>"> <?php echo $resdl->name; ?> </option> 
                                    <?php } ?>
                                </datalist>
                            </td>
                        </tr>

                        <tr>
                            <td>                                
                                Quantity
                            </td>
                            <td>
                                <input type="text" name="qty" id="qty" class="input-text" style="width: 150px;">
                            </td>
                        </tr>

                        <tr>
                            <td>                                
                                Lot NO
                            </td>
                            <td>
                                <input type="text" name="lotno" id="lotno" class="input-text" style="width: 150px;">
                            </td>
                        </tr>

                        <tr>
                            <td>                                
                                Assigned User
                            </td>
                            <td>
                                <input type="text" name="user" id="user" class="input-text" style="width: 150px;">
                            </td>
                        </tr>
                        
                        


                        <tr>
                            <td>

                            </td>
                            <td>
                                <input type="submit" class="btn" style="margin-left: 0px; width: 170px;" name="submit" value="Add Wastage">
                                <span style="color: Blue;">{{ $msg or '' }}</span>
                            </td>
                        </tr>

                    </table>
                </td>
            </form>
            <td> 
                <form action="Wastagessubmit" method="POST"> 
                    <div class="pageTableScope2" style="margin-left: 30px; border-left-color: #001092; border-left-style: solid; border-left-width: 1px; padding-left: 20px; height: 500px;">
                        <p style="float: left" class="tableHead">View Day Wastages</p>
                        <br/>

                        <table>
                            <tr>
                                <td>Date From <br/> <input type="date" class="input-text" id="date1"/></td>
                                <td>TO <br/> <input type="date" class="input-text" id="date2"/></td>
                                
                                <td>
                                    Description : <br/> <input type="text" class="input-text" id="description" list="desclistx" /> 
                                    <datalist id="desclistx">
                                        <?php
                                        $Resultdl = DB::select("select reason from wastage group by reason");
                                        foreach ($Resultdl as $resdl) {
                                            ?>
                                            <option> <?php echo $resdl->reason; ?> </option>  
                                        <?php } ?>
                                    </datalist>

                                </td>
                                <td>
                                    <input type="button" value="Search" onclick="searchExpenses()" class="btn"/>
                                </td>
                            </tr>
                            <tr>
                                <td>Type : <br/> 
                                    <select id="ssup" class="select-basic">
                                        <option value="%"></option> 

                                        <?php
                                        $Resultdl = DB::select("select * from waste_category");
                                        foreach ($Resultdl as $resdl) {
                                            ?>
                                            <option value="<?php echo $resdl->id; ?>"> <?php echo $resdl->name; ?> </option> 
                                        <?php } ?>
                                    </select>
                                </td>
                                <td>
                                    <!-- Record Date : <br/><input type="date" class="input-text" id="cdate"/> -->
                                </td>

                            </tr>

                        </table>


                        <hr/>
                        <p style="float: right;">
                            <input type="button" value="Print Table" class="btn" style="margin: 0px; width: 120px;" onclick="printGroupTable()">
                            <!--<input type="submit" name="submit" value="Update Table" class="btn" style="margin: 0px;"></p>-->

                        <table id="tg_table" border="0" cellpadding="0" cellspacing="0" >
                            <tr>
                                <td valign="top">
                                    <table id="exptable" width="900" border="1" cellpadding="0" cellspacing="0" class="TableWithBorder" style="font-family: serif;">

                                    </table> 

                                    <input type="hidden" id="tgid" name="tgid" value="">
                                </td>
                                <td width="400" valign="top">
                                    <div id="TestList">
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </form>
            </td>
            </tr>            
        </table> 
        <hr/>

        <h2 id="totexp" style="font-family: serif; color: #001092;">Total Wastages Qty. <span id="totexpamount" style="font-weight: bold;">  </span> </h2> 
        <hr/> 
    </blockquote>
    <?php
}
?>
@stop